version: '1.1'

services:
  web:
    build:
      context: .
      dockerfile: ./transport/dockerfile
    container_name: server
    volumes:
      - ./transport:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - MYSQL_HOST= server
  db:
    image: mysql:5.7
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transport
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - /var/jenkins_home/workspace/Docker_pipeline/Travelling_Managment/db_init-initdb.d:/docker-entrypoint-initdb.d

volumes:
  db_data:
