pipeline {
    agent {
        docker {
             args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    stages {
        stage('Pull Images') {
            steps {
                sh 'docker --version'
            }
        }
    }
}
