pipeline {
    agent any
    stages {
        stage('Checking Containers') {
            steps {
                sh 'sudo docker ps'
            }
        }
        stage('Closing and Cleaning Last Run'){
            steps{
                sh 'sudo docker-compose down'
                sh 'sudo docker volume rm docker_pipeline_db_data'
            }
        }
        stage('Running the new DockerCompose'){
            steps{
                sh 'sudo docker-compose build'
                sh 'sudo docker-compose up'
            }
        }
    }
}
